### ISSUE TITLE
Feature Request: weaver struct tags for weaver.WithConfig[T]

### ISSUE THREAD

**Issue by naivary** [ServiceWeaver/weaver#433]
I think it would be nice to have the option to set struct tags for a config struct e.g.

```golang
type config struct {
  Option1 string `weaver:"option_1"`
}
```

the weaver.toml file would look something like this:
```toml
["example.com/pkg/Component"]
option_1 = "foo"
```

(PS: I can also try to implement it on my own if the feature is wished and open up a pull request)
