### ISSUE TITLE
Multi Deployer Error: capture stdout EOF

### ISSUE THREAD

**Issue by naivary** [ServiceWeaver/weaver#434]
I can't run my current application in the multi mode.

weaver.toml file:
```toml
[serviceweaver]
binary = "./microtmpl"

[single]
listeners.fsHttp = {address = "localhost:9000"}

[multi]
listeners.fsHttp = {address = "localhost:9000"}

["github.com/naivary/microtmpl/fs/Fs"]
DataDir = "data"
```

Error message:
```bash
Application <application-name> error: capture stdout: EOF.
```

All files can be found here: https://github.com/naivary/microtmpl. To replicate the error clone the repository and run 
```bash
weaver multi deploy weaver.toml
```

EDIT: I tried to simplify the example using the Step-by-Step Guide in the docs. I didn't work too.

IDK what changed but works now.

**Comment by mwhittaker** [comment]
Hi @naivary, there is a known bug where the multiprocess deployer doesn't work when the app only has a main component and exits right away. Maybe you were running into that?

**Comment by naivary** [comment]
I think that was it. The question is how would you run a component without the main componenten having a reference to it? Imagine a main.go file containing the weaver.Main component and a second package for example example/foo/bar. In the second package one would impelement another component which will have a listener for http traffic. Now I would like to start the weaver application and listen for http traffic, without having a ref to the second component. Is this possible or does weaver need a reference to the component and one would have to define a interface like this
```golang
type Foo interface {
   // ... all methods defined by the component

  // Serve method to accept http traffic
  Serve(context.Context) error
}
```
And the main.go would look something like this:
```golang
type 
```

**Comment by CrlsMrls** [comment]
I run into the same error. My problem was caused because the TCP port was already used. 

@naivary, could you try to change the port from `9000` to something else like `9001`? 

```toml
[multi]
listeners.fsHttp = {address = "localhost:9001"}
```
